export default {
    "npm":{
        "registry":"https://registry.npmjs.org",
        "packages":{
            "chenyfan-os":".*",
            "chenyfan-oss":"[3-9].*",
            "pagemap":"1.4.0",
            "notyf":"3.10.0",
            "artalk":"2.8.2",
            "lxgw-wenkai-webfont":"1.1.0",
            "lxgw-wenkai-screen-webfont":"1.1.0"
        },
        "scopes":{
            "@chenyfan":{
                "cache-db":".*",
                "cdnobject":".*"
            },
            "@fancyapps":{
                "ui":"4.0.31"
            }
        },
        "asyncFile":"./data/npm.json",
        "asyncFolder":"./data/npm"
    }
}